### ISSUE TITLE
internet error msg

### ISSUE THREAD

**Issue by sgrxrx** [bagaswastu/librebook#12]
![Screenshot_2021-09-17-00-10-36-322_com triton librebook](https://user-images.githubusercontent.com/78247691/133665355-c632e86c-9803-49f3-bfde-32c4da60fff0.jpg)
doesn't even load just says error even tho my net is good. Tried vpns too nthg working.

**Comment by bgwastu** [comment]
Hi @sgrxrx, thanks for reporting the issue.

However, because of certain reason, I decided to archive this project and won't be updating librebook anymore.
For the alternative you can use [Z-Library](https://z-lib.org/) they also provide [Telegram bot](https://id1lib.org/faq.php#:~:text=How%20many%20books,books%20from%20there) if you're into it.

Thank you
